In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
#sklearn library used to split train and test model
from sklearn.model_selection import train_test_split
#Then call train_test_split function it is parameterised function
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [9]:
X_train

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={"kernel":['rbf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
#fitting the model for grid search
grid.fit(X_train,Y_train)
#regressor=SVR(kernel="precomputed",C=10)
#regressor.fit(X_train,Y_train)

C:\Users\axisi\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 40 candidates, totalling 120 fits

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    4.1s
[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:    5.7s finished
C:\Users\axisi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3,
                           epsilon=0.1, gamma='auto_deprecated', kernel='rbf',
                           max_iter=-1, shrinking=True, tol=0.001,
                           verbose=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [13]:
#print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print (re)
grid_predictions=grid.predict(X_test)
#print classification report
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,grid_predictions)
print("The R_score value for best parameter{}:".format(grid.best_params_),r_score)

The R_score value for best parameter{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}: 0.8598930084494388

In [14]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.029822,0.003593,0.007991,0.002341,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.001622,-0.097907,-0.088465,-0.062665,0.043335,36
1,0.012246,0.001650,0.005210,0.007368,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.045578,-0.050102,-0.039371,-0.014632,0.042800,32
2,0.036650,0.010342,0.010158,0.003640,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.043747,-0.054054,-0.044185,-0.018164,0.043962,34
3,0.018120,0.001982,0.004513,0.000739,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.379453,0.263743,0.270498,0.304565,0.053026,27
4,0.023569,0.001920,0.005712,0.002243,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.001551,-0.097995,-0.088478,-0.062675,0.043395,37
5,0.017890,0.001861,0.003784,0.000967,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.044344,-0.048766,-0.039184,-0.014535,0.041817,31
6,0.029858,0.007114,0.007672,0.006332,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.043460,-0.053762,-0.044135,-0.018146,0.043738,33
7,0.019048,0.002682,0.008576,0.005193,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.379453,0.263743,0.270498,0.304565,0.053026,27
8,0.049166,0.010701,0.007722,0.007658,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.280420,0.159180,0.155842,0.198481,0.057956,29
9,0.045906,0.004921,0.005071,0.003658,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.519516,0.445794,0.421048,0.462119,0.041824,22
10,0.042510,0.011090,0.013527,0.002440,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.497513,0.425077,0.420930,0.447840,0.035165,24
11,0.027847,0.001852,0.002975,0.004208,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.600824,0.573673,0.559680,0.578059,0.017081,19
12,0.027386,0.004086,0.009830,0.001494,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.280931,0.158637,0.155756,0.198441,0.058341,30
13,0.027398,0.001804,0.005083,0.000324,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.514963,0.450772,0.421861,0.462532,0.038908,21
14,0.032467,0.005331,0.008219,0.003976,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.495602,0.426898,0.421539,0.448013,0.033721,23
15,0.026104,0.004800,0.002346,0.003318,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.600824,0.573673,0.559680,0.578059,0.017081,19
16,0.042146,0.002566,0.008738,0.000868,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.713543,0.671971,0.640038,0.675184,0.030094,11
17,0.047865,0.019971,0.003997,0.002944,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.797601,0.795391,0.764729,0.785907,0.015002,8
18,0.035458,0.004601,0.013000,0.002841,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.405221,0.336416,0.349444,0.363694,0.029842,25
19,0.032905,0.001569,0.002991,0.002154,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.663978,0.673763,0.637674,0.658471,0.015239,13
20,0.041017,0.003910,0.008112,0.000746,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.713824,0.671576,0.639937,0.675112,0.030267,12
21,0.053263,0.021245,0.004857,0.000658,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.797154,0.795738,0.764963,0.785952,0.014853,7
22,0.036146,0.004025,0.010463,0.002685,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.385746,0.319360,0.346897,0.350668,0.027233,26
23,0.033595,0.001691,0.004491,0.000406,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.663978,0.673763,0.637674,0.658471,0.015239,13
24,0.038824,0.003133,0.008388,0.001989,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.794232,0.780655,0.746425,0.773770,0.020115,9
25,0.053990,0.012348,0.007344,0.002867,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.822616,0.813670,0.779845,0.805377,0.018419,3
26,0.036268,0.001356,0.010491,0.003432,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.192402,-0.162949,-0.041406,-0.132252,0.065354,38
27,0.047548,0.007939,0.005318,0.000240,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.710113,0.621857,0.634263,0.655411,0.039010,15
28,0.043663,0.001083,0.008590,0.001824,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.794443,0.780342,0.746377,0.773721,0.020174,10
29,0.067212,0.011252,0.005785,0.000523,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.821856,0.813718,0.779857,0.805144,0.018187,4
30,0.035510,0.002302,0.008924,0.000258,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.038754,-0.046722,-0.043343,-0.042940,0.003266,35
31,0.043288,0.005748,0.005928,0.002868,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.710113,0.621857,0.634263,0.655411,0.039010,15
32,0.047714,0.009324,0.007872,0.000631,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.805659,0.800880,0.768195,0.791578,0.016649,6
33,0.107990,0.029917,0.007203,0.002461,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.824951,0.814057,0.783380,0.807463,0.017600,1
34,0.039217,0.010543,0.009543,0.000484,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.935044,-0.652358,-0.912173,-0.833192,0.128209,39
35,0.075713,0.033575,0.004435,0.000629,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.710020,0.621851,0.632748,0.654873,0.039248,17
36,0.049559,0.005753,0.008269,0.000577,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.805853,0.800723,0.768175,0.791584,0.016684,5
37,0.112549,0.023137,0.006206,0.001282,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.825027,0.813966,0.783395,0.807463,0.017607,2
38,0.047945,0.019643,0.010640,0.009441,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.924846,-1.126127,-0.940265,-0.997079,0.091467,40
39,0.057021,0.021892,0.001662,0.002351,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.710020,0.621851,0.632748,0.654873,0.039248,17

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:50
BMI:40
Children:10
Sex Male 0 or 1:0
Smoker Yes 0 or 1:1

In [16]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,
smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[20806792.56949148]